### ISSUE TITLE
iconfontConf 是怎么用的。

### ISSUE THREAD

**Issue by white-ubuntu** [BelinChung/react-native-hiapp#1]
我看了你的图标的使用，你在哪里看的这么使用的？特别是value为数字。希望解答下。

**Comment by BelinChung** [comment]
也许这篇文章能帮助你
http://www.imbeta.cn/zai-react-nativezhong-you-ya-de-shi-yong-iconfont.html

**Comment by white-ubuntu** [comment]
谢谢啊，大兄弟。
