### ISSUE TITLE
undefined is not an object ...

### ISSUE THREAD

**Issue by tuanbs** [BelinChung/react-native-hiapp#7]
Hi, I got the error `undefined is not an object (evaluating '_reactNative.View.PropTypes.style')`. How can I fix it? Thanks in advance.
<img width="364" alt="screenshot 2018-10-13 09 43 53" src="https://user-images.githubusercontent.com/4801395/46897168-dfe86600-cecc-11e8-859d-3d163c2e808b.png">

**Comment by BelinChung** [comment]
fixed!
v0.2.0 upgrade react-native and other components to latest versions.

**Comment by tuanbs** [comment]
@BelinChung There's nothing in the updated version.
<img width="421" alt="Screenshot 2019-03-25 14 30 28" src="https://user-images.githubusercontent.com/4801395/54893688-06460f00-4f0b-11e9-8182-04c9cbd990fd.png">
<img width="407" alt="Screenshot 2019-03-25 14 30 37" src="https://user-images.githubusercontent.com/4801395/54893689-06dea580-4f0b-11e9-9bf9-5b76fb65413e.png">
<img width="406" alt="Screenshot 2019-03-25 14 30 48" src="https://user-images.githubusercontent.com/4801395/54893690-06dea580-4f0b-11e9-89d1-0f380a288076.png">

**Comment by BelinChung** [comment]
@tuanbs v0.2.0 is still in progress, but it will be completed soon!

**Comment by tuanbs** [comment]
@BelinChung Thanks for that. I'm new to React and I really like the way of you code this app using React Native. I learn a lot from it. It would be better if you could integrate Redux (which I struggle to understand) into this app. 👍🙂

**Comment by BelinChung** [comment]
@tuanbs Ok! 😄

**Comment by BelinChung** [comment]
@tuanbs Redux has integrated to v0.2.0(https://github.com/BelinChung/react-native-hiapp/commit/36ac6a9db9df7fd3231ca27302f3523820a77970).

**Comment by tuanbs** [comment]
@BelinChung Excellent. Thank you very much. Please keep going on your awesome work. 👍😃
