### ISSUE TITLE
the home page is blank

### ISSUE THREAD

**Issue by jetablezhu** [BelinChung/react-native-hiapp#8]
Execuse me, I find home page did not have any data.Because you did not write any function about timeline.I want to know is this your original idea or do that future?

**Comment by yifeiyin** [comment]
Hi, I am not the author of this, but have been working closely with this repo.

If you are looking at the `v0.2.0` branch of the repo, there is no tweet stuff. 

But if you checkout [`master`](https://github.com/BelinChung/react-native-hiapp/tree/master) branch (which is older), it has tweets related code such as [TweetView](https://github.com/BelinChung/react-native-hiapp/blob/master/App/Views/Tweet/index.js) and [TweetDetailView](https://github.com/BelinChung/react-native-hiapp/blob/master/App/Views/TweetDetails/index.js) (even though the name of [the class](https://github.com/BelinChung/react-native-hiapp/blob/master/App/Views/TweetDetails/index.js#L22) is not changed during copy/pasting).

**Comment by BelinChung** [comment]
fixed!
